language: go
go:
  - "1.11"
notifications:
  email:
    recipients:
      - brendan@cloudflare.com
    on_success: never
    on_failure: always

services:
  - docker

before_script:
  - docker build -t server -f devdata/Dockerfile.travis .
  - go install github.com/cloudflare/ct-log/cmd/admin/ct-log-tester

script:
  - go test -v ./...
  - ./devdata/integration-test.sh
